parameters:
    ## Top menu
    ezdemo.top_menu.content_types_exclude: [article]

    ## Footer
    # Limit for latest content in footer.
    ezdemo.footer.latest_content.limit: 7
    # LocationId for footer content object.
    ezdemo.footer.content_id: 58
    # ContentType identifiers we want to have in "latest content" part of the footer.
    ezdemo.footer.latest_content.content_types: [article]
    # Number of blog_posts displayed per page in the blog view
    ezdemo.blog.blog_post_list.limit: 10
    # Decide whether to show or hide article summary in the full view
    ezdemo.article.full_view.show_summary: true
    # Decide whether to show or hide article image in the full view
    ezdemo.article.full_view.show_image: true

    ## Cache settings
    ezdemo.cache.feed_reader_ttl: 3600
